# 初期モード
InitialMode=Direct
# 入力状態の共有
InputState=All
# 候補を縦に並べる
Vertical=True
# 用例の表示 (候補が縦並びのとき)
ExpandMode=Always
# プリエディットカーソルをプリエディットの先頭に固定する
PreeditCursorPositionAtBeginning=False
# 用例を表示するホットキー
ExpandKey=Control+Alt+H

