# encode.lua
# ============
# use default profile (makes vp8 webms)
e script-message-to encode set-timestamp

# use custom webm profile, the argument name must correspond to an existing .conf file (see script-opts/)
alt+e script-message-to encode set-timestamp encode_webm

# use custom profile
E script-message-to encode set-timestamp encode_slice


# other stuff
#=================
# cycle subtitle font
a cycle-values sub-font "A-OTF リュウミン Pro" "A-OTF 角新行書 Std L" "A-OTF 角新行書 Std M" "A-OTF 教科書ICA Pro M" "A-OTF 隷書101 Std Medium" "A-OTF 隷書E1 Std Regular" "Arial"
