keep-open=yes
sub-ass-override=yes
#"A-OTF リュウミン Pro","A-OTF 角新行書 Std L","A-OTF 角新行書 Std M","A-OTF 教科書ICA Pro M","A-OTF 隷書101 Std Medium","A-OTF 隷書E1 Std Regular","Arial"
#sub-font="A-OTF 角新行書 Std L"
#sub-ass-style-overrides=StyleName.FontName="A-OTF 角新行書 Std L"
alang=jap,ja,jp,jpn,eng,en
slang=jap,ja,jp,jpn,eng,en
