#preload = ~/画像/wallpapers/fwmc.jpg
preload = ~/Pictures/blackpixel.png
splash = false

wallpaper {
    #Monitor to display this wallpaper on. If empty, will use this wallpaper as a fallback
    monitor =

    path = ~/Pictures/blackpixel.png 

    # Determines how to display the image. Optional and defaults to cover.
    # contain|cover|tile|fill
    #fit_mode = cover
}
