# ~/.config/starship.toml # A minimal left prompt 
format = """$directory$jobs$character"""
right_format = """$all$cmd_duration$sudo$time""" 

[directory] 
fish_style_pwd_dir_length = 2 
format = '[$path]($style)[$read_only]($read_only_style) ' 
style = 'bold blue' 
[jobs] 
format = '[$symbol $number]($style)' 
symbol = '✦' 
style = 'bold blue' 
[character] 
success_symbol = '[❯](bold blue)' 
error_symbol = '[❯](bold red)' 
[time] 
disabled = false 
format = '[ $time ]($style)' 
style = 'inverted red' 
[sudo] 
format = '[ 賢者ﾀｲﾑ ]($style)' 
disabled = true 
style = 'inverted red' 
[cmd_duration] 
format = '[$duration ]($style)' 
style = 'bold red'
[git_status]
style = 'bold red'
[git_branch]
style = 'bold red'
